# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 096868ef975f84beaeaab4f86bd6076c2f8aa18584dff5cfe3ba1d22c2fbdf46842c14cfedb873fde274bc538cee3df34442d65f199d161b719b3ae1253a3db4

test:
  secret_key_base: f5195d29a3d10e69ea1fc4d10d5c347973f97568a25cb13e0a057f29532d8f4bfa061df71f33aeffdafa09c1f4f7f002b4c49f7d6141431da27095c8eb684cde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
